# dbt/dbt_project.yml
name: 'crypto_pipeline'
version: '1.0.0'
config-version: 2

profile: 'crypto_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  crypto_pipeline:
    staging:
      +schema: silver        # → เขียนลง silver schema (ตรงกับ silver.ohlcv)
      +materialized: view
    intermediate:
      +schema: silver        # → เขียนลง silver schema
      +materialized: table
    mart:
      +schema: gold          # → เขียนลง gold schema
      +materialized: table