version: 2

models:
  - name: fact_price_ohlcv
    description: "Daily OHLCV fact table — BTC, ETH, SOL"
    columns:
      - name: price_sk
        data_tests: [unique, not_null]
      - name: coin_sk
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_coin')
              field: coin_sk
              config:
                severity: warn
      - name: date_id
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
              config:
                severity: warn
      - name: close_price
        data_tests: [not_null]

  - name: dim_coin
    columns:
      - name: coin_sk
        data_tests: [unique, not_null]
      - name: coin_id
        data_tests: [unique, not_null]

  - name: dim_date
    columns:
      - name: date_id
        data_tests: [unique, not_null]